### ISSUE TITLE
Staff IT Helpdesk revamp

### ISSUE THREAD

**Issue by DanielPullan** [m-spry/Calcium#37]
It really needs redoing. Currently looks confusing and rather ugly.

**Comment by m-spry** [comment]
https://github.com/m-spry/Calcium/blob/dev/assets/include/StaffITHelpdesk/Modals.php

Modals.php has been rewriten. 3.5 might be a time where I look into this issue. I can't see too much that needs to be changed but I do plan to move away from the <table> in favour of grids. 

I also want to re-write the processes behind the staff it help desk (primarily the loan equipment events)

**Comment by m-spry** [comment]
Staff IT Helpdesk tables have now been merged into one as well as a rewrite of the system.
index.php calls to modals.php and table.php. 

- Modals.php generates out all windows and ticket submission options. 
- Table.php prints out the table which contains open and closed tickets with a simplified UI without Close/Reply/Reopen buttons to clarify what is happening when you click on a ticket is just a window where you can then decide what happens.

Closing this issue as I am content with the IT Helpdesk now for the moment.
