### ISSUE TITLE
Remind Me - Method to remove alert from navigation

### ISSUE THREAD

**Issue by m-spry** [m-spry/Calcium#50]
In its current state Remind Me won't stop reminding you in the navigation with the yellow box unless you either close the ticket or delete the comment.

Maybe the solution is to delete the RemindMe comment if the user who created the comments accesses the ticket after the timestamp listed in the comment?

**Comment by DanielPullan** [comment]
Maybe a dismiss button could remove the remind me ticket?

**Comment by m-spry** [comment]
The comment will need to be modified in some way, deleting is the easiest way about it but maybe I can edit it to remove `##RemindMe##` and replace it with `##Reminded##` just to keep the comment for record keeping and style it accordingly.

**Comment by m-spry** [comment]
When a user opens a ticket they set to be reminded about from the RemindMe table it will change the comment from ##RemindMe## to ##Reminded## which removes the flag to show the navigation icon but preserves historic reminder comments.

https://github.com/m-spry/Calcium/commit/4b4ec3eb50aea4510817404edeba06fa290643e4
