### ISSUE TITLE
Calcium 4.0 Installer

### ISSUE THREAD

**Issue by g-mandas** [m-spry/Calcium#86]
Hi,
I am trying to install Calcium on my local machine for testing with no success. I don't get any error messages. I have the following system:
System: windows 7
web server: apache 2.4
PHP Version 7.2.3
mysql version: 5.7

I have placed the files in a folder called "Calcium". I can see the "Calcium Configuration" page when I typed http://localhost/calcium/
 Completing the required fields and clicking submit returns back to http://localhost/?Configure without completing the installation and without giving any errors.
any suggestions?
thanks

**Comment by m-spry** [comment]
Hi g-mandas,

I'm currently re-writing a lot of Calcium, my repositories are the source of early access developer builds, Calcium is owned by Poole High School, their repository contains stable releases. Currently version 4 is not finished and doesn't have a working installer, this is 100% in the pipeline before its final release however I don't have a working solution for you at the moment.

Thanks for taking a look, I'll leave this issue open as a reminder to get the installer done towards the end of development
