### ISSUE TITLE
Feature: Dark Mode

### ISSUE THREAD

**Issue by m-spry** [m-spry/Calcium#9]
At some point I'll look into this requested feature.

**Comment by m-spry** [comment]
@DanielPullan feel free to look at this and make a pull if interested

**Comment by DanielPullan** [comment]
@m-spry sure, I'll see how much time it might take. I presume I can make a dark.css file, then you can put in the UI somewhere to swap to dark mode (or hide it with a konami code to prevent confusing users).

**Comment by m-spry** [comment]
something like that, it'll be a js script of sorts that just replaces classes with dark ones. maybe prefixed with 'dark-'

**Comment by m-spry** [comment]
dark.css is done, now I need to live up to my end of the bargain

**Comment by m-spry** [comment]
JS is done. @DanielPullan can manage the dark.css side. I will log issues I find here

**Comment by m-spry** [comment]
@DanielPullan 
- Items appear to be floating around on the ticketing system on the admin dashboard.
- Staff IT Helpdesk field needs some love, its completely white
- Open/Mine/Hold/Closed Ticket tables should have a hover effect.
- Some classes still have the normal modes darker blue colour. (Portfolio / body maybe?)
- Username box in top right has some colouring issues.
- Search icon has no colour
- Expanded search field has the wrong colour
- Minor dolphin fixes

**Comment by m-spry** [comment]
Added a KB shortcut. "D"

**Comment by DanielPullan** [comment]
Fixed
- Staff IT Helpdesk field needs some love, its completely white
- Username box in top right has some colouring issues.
- Search icon has no colour
- Expanded search field has the wrong colour

TODO
- Items appear to be floating around on the ticketing system on the admin dashboard.
- Open/Mine/Hold/Closed Ticket tables should have a hover effect.
- Some classes still have the normal modes darker blue colour. (Portfolio / body maybe?)

**Comment by DanielPullan** [comment]
Going to add a new class in custom.css called .ticketHeaderRow, the current plan is to replace the inline CSS with that class, in custom.css set background-color to #f0f0f0 (current value in inline css) and in dark.css set it to #2a2a2a.

**Comment by m-spry** [comment]
<img width="303" alt="screen shot 2017-01-23 at 10 19 41" src="https://cloud.githubusercontent.com/assets/1755607/22200073/7da6907c-e155-11e6-8ec1-10feec9a6437.png">
<img width="302" alt="screen shot 2017-01-23 at 10 19 35" src="https://cloud.githubusercontent.com/assets/1755607/22200075/7dc5d8c4-e155-11e6-9d33-52e1892f3cea.png">

Dark mode doesn't line up correctly

**Comment by m-spry** [comment]
<img width="1920" alt="screen shot 2017-01-23 at 10 21 24" src="https://cloud.githubusercontent.com/assets/1755607/22200135/c2c153fe-e155-11e6-8b05-46880156eb33.png">

Something between the navigation and the portfolio class has the wrong colour

**Comment by DanielPullan** [comment]
Hopefully will be a little bit closer to calling darkmode ready when these things are resolved:

- fix white outline on "go to beta build"
- fix white outline on settings li moving things
- in "manage icons" the catagory choice colour needs fixing
- user updated background needs fixing in manage users (you see it when you make a change to a user)
- change the outline on the textarea in edit notice to match the green (remove the white)
- same for the dropdown maybe?
- change table/grid lines to a light grey? removes harshness of colour
- change textarea background when on a ticket
- fix colours in printer issue ticket area
- same for projector
- remove the bulk of red in borrow equipment
- fix colours on date colour picker
- new user colour fix in helpdesk
- that blue on password reset son, nope. remove in standard calcium too

**Comment by m-spry** [comment]
Hunting for more issues:

Can we make this grey text white?

<img width="536" alt="screen shot 2017-01-31 at 09 37 50" src="https://cloud.githubusercontent.com/assets/1755607/22459594/32b25af2-e799-11e6-8a00-bdcbd08d967a.png">
<img width="550" alt="screen shot 2017-01-31 at 09 38 06" src="https://cloud.githubusercontent.com/assets/1755607/22459598/3584f726-e799-11e6-97e2-b85a1896fea8.png">

**Comment by m-spry** [comment]
Button presses appear to be white: This doesn't appear to happen on the settings dropdown. Screenshot is from Closed window when clicking buttons.

<img width="591" alt="screen shot 2017-01-31 at 09 40 42" src="https://cloud.githubusercontent.com/assets/1755607/22459673/75551be2-e799-11e6-92b6-cbff00f00635.png">

**Comment by m-spry** [comment]
This is still floating, probably shouldn't make it to release.

![screen shot 2017-01-31 at 09 42 23](https://cloud.githubusercontent.com/assets/1755607/22459733/9ffe7b90-e799-11e6-99c0-ec625b1b3841.png)
![screen shot 2017-01-31 at 09 42 16](https://cloud.githubusercontent.com/assets/1755607/22459736/a3754880-e799-11e6-8d63-a0af8f87be06.png)

**Comment by m-spry** [comment]
More reason why this shouldn't be floating:
![screen shot 2017-01-31 at 09 51 55](https://cloud.githubusercontent.com/assets/1755607/22460014/ee42ccd8-e79a-11e6-94dd-433c46211284.png)

**Comment by m-spry** [comment]
Feature has been added in Version 3.3 - Future issues with this mode should be in their own issues from this point on as this issue is in regards to its initial implementation.
